name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: MuhammadMaazA
          outputs: dist/snake.svg

      - name: Upload Snake Animation
        run: mkdir -p output && mv dist/snake.svg output/snake.svg

      - name: Commit and Push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add output/snake.svg
          git commit -m "Updated Snake Animation"
          git push
